name: Build

on:
  push:
    tags:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y phantomjs optipng
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip j2cli
          
      - run: make ci
